// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/job.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobInvokeServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Request       []byte                 `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInvokeServiceRequest) Reset() {
	*x = JobInvokeServiceRequest{}
	mi := &file_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInvokeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInvokeServiceRequest) ProtoMessage() {}

func (x *JobInvokeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInvokeServiceRequest.ProtoReflect.Descriptor instead.
func (*JobInvokeServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobInvokeServiceRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *JobInvokeServiceRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JobInvokeServiceRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *JobInvokeServiceRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JobInvokeServiceRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

type JobInvokeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInvokeServiceResponse) Reset() {
	*x = JobInvokeServiceResponse{}
	mi := &file_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInvokeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInvokeServiceResponse) ProtoMessage() {}

func (x *JobInvokeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInvokeServiceResponse.ProtoReflect.Descriptor instead.
func (*JobInvokeServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobInvokeServiceResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type JobUpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdateProgressRequest) Reset() {
	*x = JobUpdateProgressRequest{}
	mi := &file_proto_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateProgressRequest) ProtoMessage() {}

func (x *JobUpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*JobUpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobUpdateProgressRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *JobUpdateProgressRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type JobUpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdateProgressResponse) Reset() {
	*x = JobUpdateProgressResponse{}
	mi := &file_proto_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateProgressResponse) ProtoMessage() {}

func (x *JobUpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*JobUpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{3}
}

var File_proto_job_proto protoreflect.FileDescriptor

const file_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/job.proto\x12\bprotobuf\"\x8f\x01\n" +
	"\x17JobInvokeServiceRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x18\n" +
	"\arequest\x18\x05 \x01(\fR\arequest\"6\n" +
	"\x18JobInvokeServiceResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"N\n" +
	"\x18JobUpdateProgressRequest\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x03R\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\"\x1b\n" +
	"\x19JobUpdateProgressResponse2\xbc\x01\n" +
	"\x03Job\x12X\n" +
	"\rInvokeService\x12!.protobuf.JobInvokeServiceRequest\x1a\".protobuf.JobInvokeServiceResponse\"\x00\x12[\n" +
	"\x0eUpdateProgress\x12\".protobuf.JobUpdateProgressRequest\x1a#.protobuf.JobUpdateProgressResponse\"\x00B\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_proto_job_proto_rawDescOnce sync.Once
	file_proto_job_proto_rawDescData []byte
)

func file_proto_job_proto_rawDescGZIP() []byte {
	file_proto_job_proto_rawDescOnce.Do(func() {
		file_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)))
	})
	return file_proto_job_proto_rawDescData
}

var file_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_job_proto_goTypes = []any{
	(*JobInvokeServiceRequest)(nil),   // 0: protobuf.JobInvokeServiceRequest
	(*JobInvokeServiceResponse)(nil),  // 1: protobuf.JobInvokeServiceResponse
	(*JobUpdateProgressRequest)(nil),  // 2: protobuf.JobUpdateProgressRequest
	(*JobUpdateProgressResponse)(nil), // 3: protobuf.JobUpdateProgressResponse
}
var file_proto_job_proto_depIdxs = []int32{
	0, // 0: protobuf.Job.InvokeService:input_type -> protobuf.JobInvokeServiceRequest
	2, // 1: protobuf.Job.UpdateProgress:input_type -> protobuf.JobUpdateProgressRequest
	1, // 2: protobuf.Job.InvokeService:output_type -> protobuf.JobInvokeServiceResponse
	3, // 3: protobuf.Job.UpdateProgress:output_type -> protobuf.JobUpdateProgressResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_job_proto_init() }
func file_proto_job_proto_init() {
	if File_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_proto_goTypes,
		DependencyIndexes: file_proto_job_proto_depIdxs,
		MessageInfos:      file_proto_job_proto_msgTypes,
	}.Build()
	File_proto_job_proto = out.File
	file_proto_job_proto_goTypes = nil
	file_proto_job_proto_depIdxs = nil
}
